hparams={ 'dct_size': 'auto',
        'nhead': 10,
        'embed_dim': 300,
        'encoder_size': 250,
        'v_size': 200,
        'model_path':'/home/ming/NRMS/Data/model_weight/model_epoch50.pth',
        "news_file":'/home/ming/NRMS/Data/news.parquet',
        "behaviors_file":'/home/ming/NRMS/Data/MIND_train/behaviors.parquet',
        "w2v_file":'/home/ming/NRMS/Data/word2vec/all_W2vec.pkl',
        'vocab_file':'/home/ming/NRMS/Data/word2vec/glove.txt',
        'lr':1e-3,
        'epochs':50,
}