hparams={ 'dct_size': 'auto',
        'nhead': 16,
        'embed_dim': 300,
        'encoder_size': 256,
        'v_size': 200,
        'model_path':'/home/ming/NRMS/Data/model_weight/model_normal.pth',
        "news_file":'/home/ming/NRMS/Data/small_news.parquet',
        "behaviors_file":'/home/ming/NRMS/Data/MINDsmall_train/behaviors.parquet',
        "behaviors_dev_file": '/home/ming/NRMS/Data/MINDsmall_dev/behaviors.parquet',
        "w2v_file":'/home/ming/NRMS/Data/word2vec/W2vec.pkl',
        'vocab_file':'/home/ming/NRMS/Data/word2vec/glove.txt',
        'lr':1e-3,
        'epochs':10,
}